### ISSUE TITLE
densenet_configuration_4_model_checkpoint.pth.tar

### ISSUE THREAD

**Issue by imsomdev** [LidorPrototype/TableNetTable2df#3]
How can I load this model? I mean how can I download this model or clone this? Or whatever. You mentioned you didnot up this because of size but I cannot find it anywhere.

Thank you.

**Comment by LidorPrototype** [comment]
Indeed the model was too big for GitHub uploads, that's why I didn't upload it.
You can refer to the article [Detect and Extract Tabular Data From Images Using TableNet (With PyTorch)](https://betterprogramming.pub/table-detection-and-extraction-tablenet-deep-learning-model-with-pytorch-from-images-64489e92b641?gi=126ed1a330f6), follow it with the repo and you'll be able to create a model for this task too :)
